# Generated by Django 3.2 on 2021-05-10 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='acts.act'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislations', to='acts.article'),
        ),
    ]
