# Generated by Django 3.2 on 2021-05-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_auto_20210510_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='pcode',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
