# Generated by Django 3.2 on 2021-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_act_pcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='valid_state',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
